### ISSUE TITLE
more liberal license?

### ISSUE THREAD

**Issue by glyph** [appzer/python-pushsafer#3]
I was a little surprised to see a tiny SDK-type library like this under the fairly restrictive GPL 3. Would it make more sense to relicense as something like MIT? Or if you're committed to GPL, it seems like for this type of project LGPL3 would be more appropriate?

(To be clear, if I were going to use pushsafer I have no issue just writing my own API client, since I'd probably need to do so anyway to get access to the rest of the API; feel free to close if this choice was intentional, but sometimes folks choose GPL without realizing the implications for its adoption.)

**Comment by appzer** [comment]
Hi,

it's better you write you own API client. Because iam not a python developer.
When you are ready with your project you can share it with the world.

Reagrds Kevin
